services:
  menstrunation_app:
    container_name: menstrunation_spring_app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    restart: always
    networks:
      - menstrunation_net


  mariadb:
    container_name: menstrunation_db
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: menstrunation
    ports:
      - '4304:3306'
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "root", "-proot", "-e", "SELECT 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - menstrunation_net

  mariadb-test:
    container_name: menstrunation_test_db
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: menstrunation_test
    ports:
      - '4305:3306'

  phpmyadmin:
    container_name: menstrunation_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    ports:
      - '4305:80'
    environment:
      - PMA_HOST=mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - menstrunation_net
#
# menstrunation_app:
#   build: .
#   container_name: menstrunation_spring_app
# #    working_dir: /app
# #    volumes:
# #      - .:/app
# #    command: sh -c "./gradlew build --exclude-task test && java -jar build/libs/*.jar"
#   ports:
#     - "8080:8080"
#   depends_on:
#     mariadb:
#       condition: service_healthy
#     phpmyadmin:
#     condition: service_started
#   restart: unless-stopped
#
##  menstrunation_app:
##    container_name: menstrunation_spring_app
##    build:
##      context: .
##    ports:
##      - "8080:8080"
##    depends_on:
##      mariadb:
##        condition: service_healthy
##      phpmyadmin:
##        condition: service_started
##    restart: always
##    networks:
##      - menstrunation_net




networks:
  menstrunation_net:
    driver: bridge
