services:
  mariadb:
    container_name: menstrunation_db
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: menstrunation_db
    ports:
      - '4304:3306'
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "root", "-proot", "-e", "SELECT 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - menstrunation_net

  phpmyadmin:
    container_name: menstrunation_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    #    platform: linux/amd64
    ports:
      - '4305:80'
    environment:
      - PMA_HOST=mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - menstrunation_net

  menstrunation_app:
    container_name: menstrunation_spring_app
    image: eclipse-temurin:21-jdk-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: [ "sh", "-c", "apk add --no-cache findutils && ./gradlew --no-daemon clean && ./gradlew bootJar -x test --stacktrace && java -jar build/libs/*.jar" ]
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    restart: unless-stopped
    networks:
      - menstrunation_net

networks:
  menstrunation_net:
    driver: bridge