###Holt sich einen validen JWT
POST http://localhost:8080/menstrunation/api/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "ILoveBockwurst69"
}

> {%
    client.global.set("jwt", response.body.valueOf());
%}

### Aktualisiert ein Vibe-Objekt
PUT http://localhost:8080/menstrunation/api/vibe
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "id": 2,
  "anger": 999,
  "period": true,
  "blood": 2,
  "mood": [
    "testestsetstes",
    "linker",
    "Sack",
    "hat",
    "pickel"
  ]
}